services:
  - type: web
    name: bernoulli-torricelli
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
